//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dzmac.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dzmac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        // Dialog / MessageBox messages

        internal static string MacAddressInvalid {
            get { return ResourceManager.GetString("MacAddressInvalid", resourceCulture); }
        }

        internal static string MacAddressUpdateSuccess {
            get { return ResourceManager.GetString("MacAddressUpdateSuccess", resourceCulture); }
        }

        internal static string AdapterRegistryDeleteSuccess {
            get { return ResourceManager.GetString("AdapterRegistryDeleteSuccess", resourceCulture); }
        }

        internal static string NoAdaptersToExport {
            get { return ResourceManager.GetString("NoAdaptersToExport", resourceCulture); }
        }

        internal static string StartupFailed {
            get { return ResourceManager.GetString("StartupFailed", resourceCulture); }
        }

        internal static string VendorListStillLoading {
            get { return ResourceManager.GetString("VendorListStillLoading", resourceCulture); }
        }

        internal static string MacAddressRestoreSuccess {
            get { return ResourceManager.GetString("MacAddressRestoreSuccess", resourceCulture); }
        }

        internal static string MacAddressRestoreFailed {
            get { return ResourceManager.GetString("MacAddressRestoreFailed", resourceCulture); }
        }

        internal static string NotImplemented {
            get { return ResourceManager.GetString("NotImplemented", resourceCulture); }
        }

        internal static string OuiDownloadConfirmMessage {
            get { return ResourceManager.GetString("OuiDownloadConfirmMessage", resourceCulture); }
        }

        internal static string VendorListUpdated {
            get { return ResourceManager.GetString("VendorListUpdated", resourceCulture); }
        }

        internal static string ExportFailed {
            get { return ResourceManager.GetString("ExportFailed", resourceCulture); }
        }

        // Dialog titles

        internal static string MacAddressChange_Title {
            get { return ResourceManager.GetString("MacAddressChange_Title", resourceCulture); }
        }

        internal static string ConfirmRegistryDelete_Title {
            get { return ResourceManager.GetString("ConfirmRegistryDelete_Title", resourceCulture); }
        }

        internal static string DeleteAdapter_Title {
            get { return ResourceManager.GetString("DeleteAdapter_Title", resourceCulture); }
        }

        internal static string DeleteAdapterFailed_Title {
            get { return ResourceManager.GetString("DeleteAdapterFailed_Title", resourceCulture); }
        }

        internal static string ExportTextReport_Title {
            get { return ResourceManager.GetString("ExportTextReport_Title", resourceCulture); }
        }

        internal static string InitializationError_Title {
            get { return ResourceManager.GetString("InitializationError_Title", resourceCulture); }
        }

        internal static string Success_Title {
            get { return ResourceManager.GetString("Success_Title", resourceCulture); }
        }

        internal static string Failure_Title {
            get { return ResourceManager.GetString("Failure_Title", resourceCulture); }
        }

        internal static string VendorListLoading_Title {
            get { return ResourceManager.GetString("VendorListLoading_Title", resourceCulture); }
        }

        internal static string VendorListUnavailable_Title {
            get { return ResourceManager.GetString("VendorListUnavailable_Title", resourceCulture); }
        }

        internal static string MacAddressRestore_Title {
            get { return ResourceManager.GetString("MacAddressRestore_Title", resourceCulture); }
        }

        internal static string Information_Title {
            get { return ResourceManager.GetString("Information_Title", resourceCulture); }
        }

        internal static string UpdateOui_Title {
            get { return ResourceManager.GetString("UpdateOui_Title", resourceCulture); }
        }

        internal static string NetworkConnections_Title {
            get { return ResourceManager.GetString("NetworkConnections_Title", resourceCulture); }
        }

        internal static string VendorListFailed_Title {
            get { return ResourceManager.GetString("VendorListFailed_Title", resourceCulture); }
        }

        internal static string AdapterDiscoveryFailed_Title {
            get { return ResourceManager.GetString("AdapterDiscoveryFailed_Title", resourceCulture); }
        }

        internal static string AdapterStateChangeFailed_Title {
            get { return ResourceManager.GetString("AdapterStateChangeFailed_Title", resourceCulture); }
        }

        internal static string ConfirmAdapterStateChange_Title {
            get { return ResourceManager.GetString("ConfirmAdapterStateChange_Title", resourceCulture); }
        }

        internal static string UnhandledException_Title {
            get { return ResourceManager.GetString("UnhandledException_Title", resourceCulture); }
        }

        // Status bar text

        internal static string StatusNoAdaptersLoaded {
            get { return ResourceManager.GetString("StatusNoAdaptersLoaded", resourceCulture); }
        }

        internal static string StatusLoadingAdapters {
            get { return ResourceManager.GetString("StatusLoadingAdapters", resourceCulture); }
        }

        internal static string StatusAdapterLoadCancelled {
            get { return ResourceManager.GetString("StatusAdapterLoadCancelled", resourceCulture); }
        }

        internal static string StatusFailedLoadAdapters {
            get { return ResourceManager.GetString("StatusFailedLoadAdapters", resourceCulture); }
        }

        internal static string StatusLoadingVendorList {
            get { return ResourceManager.GetString("StatusLoadingVendorList", resourceCulture); }
        }

        internal static string StatusPreparingVendorList {
            get { return ResourceManager.GetString("StatusPreparingVendorList", resourceCulture); }
        }

        internal static string StatusVendorListFailed {
            get { return ResourceManager.GetString("StatusVendorListFailed", resourceCulture); }
        }

        internal static string StatusVendorListUpdateCancelled {
            get { return ResourceManager.GetString("StatusVendorListUpdateCancelled", resourceCulture); }
        }

        internal static string StatusVendorListUpdateFailed {
            get { return ResourceManager.GetString("StatusVendorListUpdateFailed", resourceCulture); }
        }

        internal static string StatusDownloadingOui {
            get { return ResourceManager.GetString("StatusDownloadingOui", resourceCulture); }
        }

        internal static string StatusReady {
            get { return ResourceManager.GetString("StatusReady", resourceCulture); }
        }

        // Fallback display text

        internal static string FallbackNoIpv4Gateway {
            get { return ResourceManager.GetString("FallbackNoIpv4Gateway", resourceCulture); }
        }

        internal static string FallbackNoIpv4DnsServer {
            get { return ResourceManager.GetString("FallbackNoIpv4DnsServer", resourceCulture); }
        }

        internal static string FallbackNoIpv6Gateway {
            get { return ResourceManager.GetString("FallbackNoIpv6Gateway", resourceCulture); }
        }

        internal static string FallbackNoIpv6DnsServer {
            get { return ResourceManager.GetString("FallbackNoIpv6DnsServer", resourceCulture); }
        }

        internal static string FallbackNoIpv4Address {
            get { return ResourceManager.GetString("FallbackNoIpv4Address", resourceCulture); }
        }

        internal static string FallbackNoIpv6Address {
            get { return ResourceManager.GetString("FallbackNoIpv6Address", resourceCulture); }
        }

        // Performance panel labels

        internal static string PerfReceivedResolving {
            get { return ResourceManager.GetString("PerfReceivedResolving", resourceCulture); }
        }

        internal static string PerfSpeedWaiting {
            get { return ResourceManager.GetString("PerfSpeedWaiting", resourceCulture); }
        }

        internal static string PerfSentResolving {
            get { return ResourceManager.GetString("PerfSentResolving", resourceCulture); }
        }

        internal static string PerfReceivedUnavailable {
            get { return ResourceManager.GetString("PerfReceivedUnavailable", resourceCulture); }
        }

        internal static string PerfSpeedUnavailable {
            get { return ResourceManager.GetString("PerfSpeedUnavailable", resourceCulture); }
        }

        internal static string PerfSentUnavailable {
            get { return ResourceManager.GetString("PerfSentUnavailable", resourceCulture); }
        }

        internal static string PerfReceivedWaiting {
            get { return ResourceManager.GetString("PerfReceivedWaiting", resourceCulture); }
        }

        internal static string PerfSentWaiting {
            get { return ResourceManager.GetString("PerfSentWaiting", resourceCulture); }
        }

        internal static string PerfReceivedZero {
            get { return ResourceManager.GetString("PerfReceivedZero", resourceCulture); }
        }

        internal static string PerfSpeedZero {
            get { return ResourceManager.GetString("PerfSpeedZero", resourceCulture); }
        }

        internal static string PerfSentZero {
            get { return ResourceManager.GetString("PerfSentZero", resourceCulture); }
        }

        // Other UI text

        internal static string ToggleDisableAdapter {
            get { return ResourceManager.GetString("ToggleDisableAdapter", resourceCulture); }
        }

        internal static string ToggleEnableAdapter {
            get { return ResourceManager.GetString("ToggleEnableAdapter", resourceCulture); }
        }

        internal static string ExportFileFilter {
            get { return ResourceManager.GetString("ExportFileFilter", resourceCulture); }
        }

        // CLI error messages

        internal static string CliMissingConnectionName {
            get { return ResourceManager.GetString("CliMissingConnectionName", resourceCulture); }
        }

        internal static string CliRestoreOriginalFailed {
            get { return ResourceManager.GetString("CliRestoreOriginalFailed", resourceCulture); }
        }

        internal static string CliUpdateMacFailed {
            get { return ResourceManager.GetString("CliUpdateMacFailed", resourceCulture); }
        }

        internal static string CliEnableDhcpFailed {
            get { return ResourceManager.GetString("CliEnableDhcpFailed", resourceCulture); }
        }

        internal static string CliSetIpv4Failed {
            get { return ResourceManager.GetString("CliSetIpv4Failed", resourceCulture); }
        }

        internal static string CliSetGatewayFailed {
            get { return ResourceManager.GetString("CliSetGatewayFailed", resourceCulture); }
        }

        internal static string CliSetDnsFailed {
            get { return ResourceManager.GetString("CliSetDnsFailed", resourceCulture); }
        }

        internal static string CliDisableAdapterFailed {
            get { return ResourceManager.GetString("CliDisableAdapterFailed", resourceCulture); }
        }

        internal static string CliEnableAdapterFailed {
            get { return ResourceManager.GetString("CliEnableAdapterFailed", resourceCulture); }
        }

        internal static string CliResetAdapterFailed {
            get { return ResourceManager.GetString("CliResetAdapterFailed", resourceCulture); }
        }

        internal static string CliDuplicateMacOption {
            get { return ResourceManager.GetString("CliDuplicateMacOption", resourceCulture); }
        }

        internal static string CliInvalidDnsValue {
            get { return ResourceManager.GetString("CliInvalidDnsValue", resourceCulture); }
        }

        internal static string CliUnsupportedOption {
            get { return ResourceManager.GetString("CliUnsupportedOption", resourceCulture); }
        }
    }
}
